/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package reserva;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import principal.Principal;

/**
 *
 * @author aplo612
 */
public class Boleta extends javax.swing.JFrame {
    ModeloVuelo obtlineaaerea = new ModeloVuelo();
    ModeloHotel obthotel = new ModeloHotel();
    ArrayList<Vuelo> listaLineaAerea = obtlineaaerea.obtenerLineaAerea();
    ArrayList<Hotel> listaHotel = obthotel.obtenerHotel();
    /**
     * Creates new form Boleta
     */
    public Boleta(int idvueloida,int idvuelovuelta,int idhotel,String asientosIda,String asientosVuelta) {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
        llenarDatos(idvueloida,asientosIda,idvuelovuelta,asientosVuelta,idhotel);
        //si(asientosIda);
    }
    
    public String setearPaises(int pais){
        ModeloPaises obtpaises = new ModeloPaises();
        ArrayList<Paises> listapaises = obtpaises.obtenerPais();
        String strPais = "";
        for(int i=0;i<listapaises.size();i++){
            if(listapaises.get(i).getIdPais()==pais){
                strPais = listapaises.get(i).getPais();
            } 
        }
        return strPais;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        labelPrecioVuelta = new javax.swing.JLabel();
        labelHoraVuelta = new javax.swing.JLabel();
        labelAsientosVuelta = new javax.swing.JLabel();
        labelEmpresaVuelta = new javax.swing.JLabel();
        labelPaisesVuelta = new javax.swing.JLabel();
        labelx6 = new javax.swing.JLabel();
        labelx5 = new javax.swing.JLabel();
        labelx4 = new javax.swing.JLabel();
        labelx7 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        labelTotalIda = new javax.swing.JLabel();
        labelTotalVuelta = new javax.swing.JLabel();
        labelTotalHotel = new javax.swing.JLabel();
        labelTotalFinal = new javax.swing.JLabel();
        labelTotalIda1 = new javax.swing.JLabel();
        labelTotalIda2 = new javax.swing.JLabel();
        labelTotalIda3 = new javax.swing.JLabel();
        labelTotalIda4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelNombreHotel = new javax.swing.JLabel();
        labelValoracionHotel = new javax.swing.JLabel();
        labelPrecioHotel = new javax.swing.JLabel();
        labelCantHotel = new javax.swing.JLabel();
        labelx10 = new javax.swing.JLabel();
        labelx8 = new javax.swing.JLabel();
        labelx9 = new javax.swing.JLabel();
        labelx11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelEmpresaIda = new javax.swing.JLabel();
        labelHoraIda = new javax.swing.JLabel();
        labelPrecioIda = new javax.swing.JLabel();
        labelAsientosIda = new javax.swing.JLabel();
        labelPaisesIda = new javax.swing.JLabel();
        labelx = new javax.swing.JLabel();
        labelx1 = new javax.swing.JLabel();
        labelx2 = new javax.swing.JLabel();
        labelx3 = new javax.swing.JLabel();
        btnPagar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setPreferredSize(new java.awt.Dimension(425, 270));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel2.setText("Vuelo Vuelta");

        labelPrecioVuelta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPrecioVuelta.setText("jLabel3");

        labelHoraVuelta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelHoraVuelta.setText("jLabel3");

        labelAsientosVuelta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAsientosVuelta.setText("jLabel3");

        labelEmpresaVuelta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmpresaVuelta.setText("jLabel3");

        labelPaisesVuelta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPaisesVuelta.setText("jLabel3");

        labelx6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx6.setText("Precio:");

        labelx5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx5.setText("Hora:");

        labelx4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx4.setText("Empresa:");

        labelx7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx7.setText("Asientos:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(125, 125, 125)
                        .addComponent(labelPaisesVuelta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelx4)
                            .addComponent(labelx5)
                            .addComponent(labelx6)
                            .addComponent(labelx7))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAsientosVuelta)
                            .addComponent(labelPrecioVuelta)
                            .addComponent(labelHoraVuelta)
                            .addComponent(labelEmpresaVuelta))))
                .addContainerGap(204, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPaisesVuelta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelEmpresaVuelta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelHoraVuelta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPrecioVuelta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelAsientosVuelta))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(labelx4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelx5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelx6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelx7)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel4.setText("BOLETA");

        labelTotalIda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalIda.setText("jLabel3");

        labelTotalVuelta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalVuelta.setText("jLabel3");

        labelTotalHotel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalHotel.setText("jLabel3");

        labelTotalFinal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalFinal.setText("jLabel3");

        labelTotalIda1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalIda1.setText("Subtotal Ida:");

        labelTotalIda2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalIda2.setText("Subtotal Hotel:");

        labelTotalIda3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalIda3.setText("Subtotal Vuelta:");

        labelTotalIda4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelTotalIda4.setText("Total:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(122, 122, 122))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalIda1)
                    .addComponent(labelTotalIda4)
                    .addComponent(labelTotalIda3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotalIda2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTotalHotel)
                    .addComponent(labelTotalFinal)
                    .addComponent(labelTotalVuelta)
                    .addComponent(labelTotalIda))
                .addGap(100, 100, 100))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalIda)
                    .addComponent(labelTotalIda1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalVuelta)
                    .addComponent(labelTotalIda3))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalHotel)
                    .addComponent(labelTotalIda2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTotalFinal)
                    .addComponent(labelTotalIda4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel4.setPreferredSize(new java.awt.Dimension(425, 270));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Hotel");

        labelNombreHotel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelNombreHotel.setText("jLabel3");

        labelValoracionHotel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelValoracionHotel.setText("jLabel3");

        labelPrecioHotel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPrecioHotel.setText("jLabel3");

        labelCantHotel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelCantHotel.setText("jLabel3");

        labelx10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx10.setText("Precio:");

        labelx8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx8.setText("Nombre Hotel:");

        labelx9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx9.setText("Valoracion:");

        labelx11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx11.setText("Cant. Habitaciones:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelx8)
                            .addComponent(labelx9)
                            .addComponent(labelx10)
                            .addComponent(labelx11))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCantHotel)
                            .addComponent(labelPrecioHotel)
                            .addComponent(labelValoracionHotel)
                            .addComponent(labelNombreHotel)))
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelNombreHotel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelValoracionHotel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPrecioHotel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelCantHotel))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(labelx8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelx9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelx10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelx11)))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel5.setPreferredSize(new java.awt.Dimension(425, 270));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel1.setText("Vuelo Ida");

        labelEmpresaIda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelEmpresaIda.setText("jLabel3");

        labelHoraIda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelHoraIda.setText("jLabel3");

        labelPrecioIda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPrecioIda.setText("jLabel3");

        labelAsientosIda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelAsientosIda.setText("jLabel3");

        labelPaisesIda.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelPaisesIda.setText("jLabel3");

        labelx.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx.setText("Empresa:");

        labelx1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx1.setText("Hora:");

        labelx2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx2.setText("Precio:");

        labelx3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelx3.setText("Asientos:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(144, 144, 144)
                        .addComponent(labelPaisesIda))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelx)
                            .addComponent(labelx1)
                            .addComponent(labelx2)
                            .addComponent(labelx3))
                        .addGap(99, 99, 99)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelAsientosIda)
                            .addComponent(labelPrecioIda)
                            .addComponent(labelHoraIda)
                            .addComponent(labelEmpresaIda))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPaisesIda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpresaIda)
                    .addComponent(labelx))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelHoraIda)
                    .addComponent(labelx1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPrecioIda)
                    .addComponent(labelx2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAsientosIda)
                    .addComponent(labelx3))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnPagar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnPagar.setText("RESERVAR");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
                
        obtlineaaerea.sobreescribirLineaAerea(listaLineaAerea);
        JOptionPane.showMessageDialog(null,"Se ha reservado correctamente", "Mensaje en la barra de titulo", JOptionPane.WARNING_MESSAGE);
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnPagarActionPerformed
    
    public void llenarDatos(int ida,String asientosIda,int vuelta,String asientosVuelta,int hotel){
        
        int cont = 0;
        int contv = 0;
        for(int i=0;i<listaLineaAerea.size();i++){
            if(listaLineaAerea.get(i).getIdVuelo()==ida){
                String origen = setearPaises(listaLineaAerea.get(i).getOrigen());
                String destino = setearPaises(listaLineaAerea.get(i).getDestino());
                labelPaisesIda.setText(origen+" -> "+destino);
                labelEmpresaIda.setText(listaLineaAerea.get(i).getNombreAerolinea());
                labelHoraIda.setText(listaLineaAerea.get(i).getHora());
                String precio = String.valueOf(listaLineaAerea.get(i).getPrecio());
                labelPrecioIda.setText(precio);
                labelAsientosIda.setText(asientosIda);
                
                String[] items = asientosIda.split(", ");
                for(int x = 0;x<listaLineaAerea.get(i).getAsientos().size();x++){
                    for (String item : items) {
                        if (listaLineaAerea.get(i).getAsientos().get(x).getAsiento() == Integer.parseInt(item)) {
                            listaLineaAerea.get(i).getAsientos().get(x).setDisponibilidad(false);
                            cont++;
                        }  
                    }
                }
                Float totalida = (Float)(listaLineaAerea.get(i).getPrecio()*cont);
                labelTotalIda.setText(String.valueOf(totalida));
            }
        }
        for(int i=0;i<listaLineaAerea.size();i++){
            if(listaLineaAerea.get(i).getIdVuelo()==vuelta){
                String origen = setearPaises(listaLineaAerea.get(i).getOrigen());
                String destino = setearPaises(listaLineaAerea.get(i).getDestino());
                labelPaisesVuelta.setText(origen+" -> "+destino);
                labelEmpresaVuelta.setText(listaLineaAerea.get(i).getNombreAerolinea());
                labelHoraVuelta.setText(listaLineaAerea.get(i).getHora());
                String precio = String.valueOf(listaLineaAerea.get(i).getPrecio());
                labelPrecioVuelta.setText(precio);
                labelAsientosVuelta.setText(asientosVuelta);
                
                String[] items = asientosVuelta.split(", ");
                for(int x = 0;x<listaLineaAerea.get(i).getAsientos().size();x++){
                    for (String item : items) {
                        if (listaLineaAerea.get(i).getAsientos().get(x).getAsiento() == Integer.parseInt(item)) {
                            listaLineaAerea.get(i).getAsientos().get(x).setDisponibilidad(false);
                            contv++;
                        }  
                    }
                }
                Float totalvuelta = (Float)(listaLineaAerea.get(i).getPrecio()*contv);
                labelTotalVuelta.setText(String.valueOf(totalvuelta));
            }
        }
        for(int i=0;i<listaHotel.size();i++){
            if(listaHotel.get(i).getIdHotel()==hotel){
                labelNombreHotel.setText(listaHotel.get(i).getNombreHotel());
                String val = String.valueOf(listaHotel.get(i).getValoracion());
                labelValoracionHotel.setText(val);
                String pre = String.valueOf(listaHotel.get(i).getPrecio());
                labelPrecioHotel.setText(pre);
                labelCantHotel.setText(String.valueOf(cont));
                Float totalHotel = (Float)(listaHotel.get(i).getPrecio()*cont);
                labelTotalHotel.setText(String.valueOf(totalHotel));
            }
        }
        float pi = Float.valueOf(labelTotalIda.getText());
        float pv = Float.valueOf(labelTotalVuelta.getText());
        float ph = Float.valueOf(labelTotalHotel.getText());
                
        labelTotalFinal.setText(String.valueOf(pi+pv+ph));
    }
    
    public void si(String asientos){
        ModeloVuelo obtlineaaerea = new ModeloVuelo();
        ModeloHotel obthotel = new ModeloHotel();
        ArrayList<Vuelo> listaLineaAerea = obtlineaaerea.obtenerLineaAerea();
        ArrayList<Hotel> listaHotel = obthotel.obtenerHotel();
        
        String[] items = asientos.split(", ");
        
        for(int i = 0;i<items.length;i++){
            System.out.println(items[i]);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boleta(0,4,0,"3, 4, 9, 10, 11","2").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPagar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel labelAsientosIda;
    private javax.swing.JLabel labelAsientosVuelta;
    private javax.swing.JLabel labelCantHotel;
    private javax.swing.JLabel labelEmpresaIda;
    private javax.swing.JLabel labelEmpresaVuelta;
    private javax.swing.JLabel labelHoraIda;
    private javax.swing.JLabel labelHoraVuelta;
    private javax.swing.JLabel labelNombreHotel;
    private javax.swing.JLabel labelPaisesIda;
    private javax.swing.JLabel labelPaisesVuelta;
    private javax.swing.JLabel labelPrecioHotel;
    private javax.swing.JLabel labelPrecioIda;
    private javax.swing.JLabel labelPrecioVuelta;
    private javax.swing.JLabel labelTotalFinal;
    private javax.swing.JLabel labelTotalHotel;
    private javax.swing.JLabel labelTotalIda;
    private javax.swing.JLabel labelTotalIda1;
    private javax.swing.JLabel labelTotalIda2;
    private javax.swing.JLabel labelTotalIda3;
    private javax.swing.JLabel labelTotalIda4;
    private javax.swing.JLabel labelTotalVuelta;
    private javax.swing.JLabel labelValoracionHotel;
    private javax.swing.JLabel labelx;
    private javax.swing.JLabel labelx1;
    private javax.swing.JLabel labelx10;
    private javax.swing.JLabel labelx11;
    private javax.swing.JLabel labelx2;
    private javax.swing.JLabel labelx3;
    private javax.swing.JLabel labelx4;
    private javax.swing.JLabel labelx5;
    private javax.swing.JLabel labelx6;
    private javax.swing.JLabel labelx7;
    private javax.swing.JLabel labelx8;
    private javax.swing.JLabel labelx9;
    // End of variables declaration//GEN-END:variables
}
