/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import principal.Principal;
import java.awt.Color;
import java.util.List;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author USUARIO
 */
public class LoginReg extends javax.swing.JFrame {
    
    List<Usuario> listaUsuarios = new ArrayList<Usuario>();
    
    

    /**
     * Creates new form LoginReg
     */
    public LoginReg() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        //Mandamos el nombre del Jlabel y la ruta de ubicacion
        rsscalelabel.RSScaleLabel.setScaleLabel(portada, "src/imagenes/portada.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(iconlogin, "src/imagenes/icono.png");
        rsscalelabel.RSScaleLabel.setScaleLabel(labelLog, "src/imagenes/logicon.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        portada = new javax.swing.JLabel();
        iconlogin = new javax.swing.JLabel();
        nombreEmpre = new javax.swing.JLabel();
        usuariotexto = new javax.swing.JLabel();
        txtUsu = new javax.swing.JTextField();
        separadorUsu = new javax.swing.JSeparator();
        labelcontraseña = new javax.swing.JLabel();
        separadorPass = new javax.swing.JSeparator();
        txtPass = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        errorUsu = new javax.swing.JLabel();
        labelLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        back.setBackground(new java.awt.Color(255, 255, 255));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        portada.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        back.add(portada, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 410));
        back.add(iconlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 40, 40));

        nombreEmpre.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        nombreEmpre.setText("ATERRIZA");
        back.add(nombreEmpre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 210, 40));

        usuariotexto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        usuariotexto.setText("USUARIO");
        back.add(usuariotexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        txtUsu.setForeground(new java.awt.Color(204, 204, 204));
        txtUsu.setText("Ingrese Usuario");
        txtUsu.setBorder(null);
        txtUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtUsuMousePressed(evt);
            }
        });
        txtUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuActionPerformed(evt);
            }
        });
        back.add(txtUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 230, 30));

        separadorUsu.setForeground(new java.awt.Color(0, 0, 0));
        back.add(separadorUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 220, -1));

        labelcontraseña.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        labelcontraseña.setText("CONTRASEÑA");
        back.add(labelcontraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        separadorPass.setForeground(new java.awt.Color(0, 0, 0));
        back.add(separadorPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 220, -1));

        txtPass.setForeground(new java.awt.Color(204, 204, 204));
        txtPass.setText("jPasswordField1");
        txtPass.setBorder(null);
        txtPass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtPassMousePressed(evt);
            }
        });
        back.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 220, 30));

        btnIniciar.setBackground(new java.awt.Color(153, 255, 255));
        btnIniciar.setText("Iniciar");
        btnIniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarMouseExited(evt);
            }
        });
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        back.add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 90, 40));

        btnRegistrar.setBackground(new java.awt.Color(153, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseExited(evt);
            }
        });
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        back.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 350, 90, 40));

        errorUsu.setForeground(new java.awt.Color(255, 0, 0));
        back.add(errorUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 320, 220, 20));
        back.add(labelLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, 90, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

        this.dispose();
        Registro reg= new Registro();
        reg.setVisible(true);   

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
       
        Principal principal=new Principal();
        
        //LECTURA DE ARCHIVO
        try{
            File archivo = new File("registros.txt");
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            
            String linea;
            
            while((linea=br.readLine())!=null){
                String nomusuario=br.readLine();
                String pass=br.readLine();
                
                Usuario usuario = new Usuario(nomusuario,pass,linea);
                listaUsuarios.add(usuario);
            }
            
            //VERIFICACION DE DATOS PARA INICIAR SESION Y ABRIR SEGUNDA VENTANA
            if (txtUsu!=null && txtPass!=null){
                for(int i=0;i<listaUsuarios.size();i++){
                    if(txtUsu.getText().equals(listaUsuarios.get(i).getNombreUsuario()) && String.valueOf(txtPass.getPassword()).equals(listaUsuarios.get(i).getPasswordUsuario())){ 
                        principal.setVisible(true);
                        this.dispose();
                        break;
                    }
                errorUsu.setText("Usuario y/o contraseña incorrecta");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Informacion Incompleta", "Inicio Erroneo", JOptionPane.WARNING_MESSAGE);
            }
            
        }catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnRegistrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseEntered

        btnRegistrar.setBackground(new Color(0, 204, 204));

    }//GEN-LAST:event_btnRegistrarMouseEntered

    private void btnRegistrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseExited
       
        btnRegistrar.setBackground(Color.white);
        
    }//GEN-LAST:event_btnRegistrarMouseExited

    private void btnIniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseEntered

        btnIniciar.setBackground(new Color(0, 204, 204));

    }//GEN-LAST:event_btnIniciarMouseEntered

    private void btnIniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarMouseExited

        btnIniciar.setBackground(Color.white);

    }//GEN-LAST:event_btnIniciarMouseExited

    private void txtUsuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuMousePressed

        txtUsu.setText("");
        txtUsu.setForeground(Color.black);
      
    }//GEN-LAST:event_txtUsuMousePressed

    private void txtPassMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPassMousePressed
  
        txtPass.setText("");
        txtPass.setForeground(Color.black);
        
    }//GEN-LAST:event_txtPassMousePressed

    private void txtUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                LoginReg log= new LoginReg();
                log.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel errorUsu;
    private javax.swing.JLabel iconlogin;
    private javax.swing.JLabel labelLog;
    private javax.swing.JLabel labelcontraseña;
    private javax.swing.JLabel nombreEmpre;
    private javax.swing.JLabel portada;
    private javax.swing.JSeparator separadorPass;
    private javax.swing.JSeparator separadorUsu;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUsu;
    private javax.swing.JLabel usuariotexto;
    // End of variables declaration//GEN-END:variables
}
