/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package login;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class Registro extends javax.swing.JFrame {
    
    List<Usuario> listaUsuarios = new ArrayList<Usuario>();

    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        
        this.setLocationRelativeTo(null);
        
        //Mandamos el nombre del Jlabel y la ruta de ubicacion
        rsscalelabel.RSScaleLabel.setScaleLabel(iconReg, "src/imagenes/registroicon.png");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        iconReg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnomReg = new javax.swing.JTextField();
        txtusuReg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtpassReg = new javax.swing.JPasswordField();
        btnRegistroReg = new javax.swing.JButton();
        errorUsu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(iconReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 80, 80));

        jLabel2.setText("Nombre");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        jLabel3.setText("Contraseña");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));
        jPanel1.add(txtnomReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, 30));

        txtusuReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtusuRegActionPerformed(evt);
            }
        });
        jPanel1.add(txtusuReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 250, 30));

        jLabel4.setText("Usuario");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        txtpassReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassRegActionPerformed(evt);
            }
        });
        jPanel1.add(txtpassReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 250, 30));

        btnRegistroReg.setText("Registrar");
        btnRegistroReg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRegistroRegMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRegistroRegMouseExited(evt);
            }
        });
        btnRegistroReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroRegActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistroReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 110, 30));

        errorUsu.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(errorUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 250, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtpassRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassRegActionPerformed

    private void txtusuRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtusuRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtusuRegActionPerformed

    private void btnRegistroRegMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroRegMouseEntered

        btnRegistroReg.setBackground(new Color(0, 204, 204));

    }//GEN-LAST:event_btnRegistroRegMouseEntered

    private void btnRegistroRegMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistroRegMouseExited

        btnRegistroReg.setBackground(Color.white);

    }//GEN-LAST:event_btnRegistroRegMouseExited

    private void btnRegistroRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroRegActionPerformed

        try{
           
            //TOMA DE DATOS
            String nombreNew=txtnomReg.getText();
            String usuarioNew=txtusuReg.getText();
            String passNew=String.valueOf(txtpassReg.getPassword());
            
            //LECTURA
            File archivo = new File("registros.txt");
            FileReader fr = new FileReader(archivo);
            BufferedReader br = new BufferedReader(fr);
            
            String linea;
            
            while((linea=br.readLine())!=null){
                String nomusuario=br.readLine();
                String pass=br.readLine();
                
                Usuario usuario = new Usuario(nomusuario,pass,linea);
                listaUsuarios.add(usuario);
            }
            
            Boolean estado=false; //Estado (false) = no registrado | (true) = registrado
            
            //VALIDACION DE CAMPOS RELLENADOS
            if(nombreNew.equals("") || usuarioNew.equals("") || passNew.equals("")){
                errorUsu.setText("Rellena los campos");
                estado=true;
            }
            
            //VERIFICACION DE EXISTENCIA DE USUARIO
            for(int i=0;i<listaUsuarios.size();i++){
                if(listaUsuarios.get(i).getNombreUsuario().equals(usuarioNew)){
                    errorUsu.setText("Usuario Existente");
                    estado=true;
                    break;
                }
            }
            
            //ESCRITURA DE USUARIO
            if(estado==false){
                    PrintWriter writer = new PrintWriter(new BufferedWriter(new FileWriter("registros.txt", true)));
            
                    writer.println(nombreNew);
                    writer.println(usuarioNew);
                    writer.println(passNew);
                    writer.close();
            
                    JOptionPane.showMessageDialog(null, "USUARIO REGISTRADO CON EXITO!!!");
            
                    this.dispose();
                    LoginReg login=new LoginReg();
                    login.setVisible(true);
                    
            }
            
            
            
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistroRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistroReg;
    private javax.swing.JLabel errorUsu;
    private javax.swing.JLabel iconReg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtnomReg;
    private javax.swing.JPasswordField txtpassReg;
    private javax.swing.JTextField txtusuReg;
    // End of variables declaration//GEN-END:variables
}
